# Generated by Django 4.0.1 on 2022-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('cafe_positio', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
